Feat/container
ant-design/ant-design-mini pull request #101
Opened 2022-05-17 09:57 UTC by Sxs7513

Container 组件

2022-05-19 08:47 UTC, wyj580231 commented on src/Container/ContainerHeader/index.less
> +            width: 48 * @rpx;
title过长时是不是会压缩image的宽度，加个flex- shrink？

2022-05-26 07:13 UTC, miaodongqing commented on src/Container/ContainerHeader/index.js
> +Page({
建议index.js => index.ts, 与其他组件保持统一

2022-05-26 07:13 UTC, miaodongqing commented on src/Container/index.less
> +
注释的大段代码建议删除

2022-05-26 07:13 UTC, miaodongqing commented on src/Container/index.ts
> +
![image](https://user-images.githubusercontent.com/1175798/170437261-0b5a024d-56ff-4a9f-935f-157dada4ba0a.png)

不用的import建议删除

2022-05-31 15:11 UTC, imsenyu requested changes

2022-05-31 15:11 UTC, imsenyu commented on src/Container/ContainerHeader/index.ts
> +    data: {}
emmm?

2022-05-31 15:11 UTC, imsenyu commented on src/Container/index.axml
> +      <slot name="box1" />
虽然不理解为什么要搞 3 个 slot 。。。

2022-05-31 15:11 UTC, imsenyu commented on src/Container/index.md
> +| box1    | 多盒子模式第一个盒子 |
为啥要这么设计。。。

2022-06-02 09:38 UTC, Sxs7513 commented on src/Container/index.axml
> +      <slot name="box1" />
稿子里画了三个box，我左思右想似乎只有这么个办法。。

2022-06-02 09:39 UTC, Sxs7513 commented on src/Container/index.md
> +| box1    | 多盒子模式第一个盒子 |
同上

2022-06-07 02:31 UTC, miaodongqing approved these changes

2022-06-08 07:13 UTC, imsenyu submitted a review, later dismissed

2022-06-13 07:41 UTC, closed without merging