feat(FloatPanel): new Component
ant-design/ant-design-mini pull request #102
Opened 2022-05-17 10:02 UTC by Sxs7513

浮动面板组件

2022-05-26 06:29 UTC, miaodongqing commented on demo/pages/FloatPanel/index.axml
> +    <Button class="button" onTap="handleToggleMask" inlineSize="small" inline>
demo点击该按钮无效（PS： Button => button）

2022-05-26 06:29 UTC, miaodongqing commented on src/FloatPanel/index.less
> +    background-color: transparent;
这里tab是四个空格，能调回2个空格吗？

2022-05-26 06:29 UTC, miaodongqing commented on src/FloatPanel/index.md
> +# FloatPanel 滑动面板
FloatPanel强依赖 sjs属性监听等能力，建议使用说明上，告知用户最低appx支持版本2.7.7

2022-05-26 06:29 UTC, miaodongqing commented on src/FloatPanel/index.md
> +| className | string | 否 | - | 组件根节点类 |
className属性不太重要，建议放在API列表的最后一个属性介绍

2022-05-26 06:29 UTC, miaodongqing commented on src/FloatPanel/index.ts
> +        didMount: false
didMount 建议换成didMouted

2022-05-26 06:29 UTC, miaodongqing commented on src/FloatPanel/index.ts
> +                    success: res => {
fail回调也处理一下

2022-05-26 06:29 UTC, miaodongqing commented on src/FloatPanel/index.axml
> +<view class="amd-swiper-box {{className || ''}}" style="height: {{ height || 0 }}px;"
组件的类名一般是amd-floatpanel开始，这里为什么使用 的是 amd-swiper？

2022-05-31 15:14 UTC, imsenyu commented on src/FloatPanel/index.ts
> +        async calHeight(sys) {
calculateHeight 写全。。

2022-05-31 15:17 UTC, imsenyu commented on src/FloatPanel/index.ts
> +        if (!sys) {
如果就为了拿 windowHeight，其实建议去 sjs 做全屏样式计算。。

2022-06-02 05:43 UTC, Sxs7513 commented on src/FloatPanel/index.ts
> +        this.calHeight(sys)
需要从 props 获取用户自定义的高度，在 sjs 里应该拿不到 props。把 props 传到 sjs 里感觉有点。。

2022-06-02 05:43 UTC, Sxs7513 commented on src/FloatPanel/index.ts
> +        if (!sys) {
同上

2022-06-07 14:13 UTC, miaodongqing approved these changes

2022-06-08 07:16 UTC, imsenyu requested changes

2022-06-08 07:16 UTC, imsenyu commented on src/FloatPanel/index.sjs
> +let scrollViewScrollStarted = false;
需要考虑多个实例的状态独立么

2022-06-08 07:16 UTC, imsenyu commented on src/FloatPanel/index.ts
> +  UP: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEUAAAAYCAYAAACsnTAAAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAARaADAAQAAAABAAAAGAAAAAC6nCo2AA
这样的话 setData 数据传输量会特别大，内置的 type 传递 type 然后 从 sjs 取吧

2022-06-13 07:54 UTC, miaodongqing approved these changes

2022-06-14 02:12 UTC, imsenyu approved these changes

2022-06-14 12:23 UTC, merged