feat(tree-select): new component
ant-design/ant-design-mini pull request #107
Opened 2022-05-19 14:40 UTC by Alpsli

2022-05-26 02:54 UTC, miaodongqing commented on src/TreeSelect/index.ts
> +    if (prevProps.options !== this.props.options) {
组件没有响应value的变更， 组件外部更改value无效

2022-05-26 02:54 UTC, miaodongqing commented on src/TreeSelect/index.ts
> +            this.props.onChange?.(selectedList.map(n => n.value));
props.onChange给的默认参数只有value， 建议第二个参数把label也透出， 如, 假设value是拼音拼写，建议
第一个参数：['zhejiang', 'hangzhou']
第二个参数[{label: '浙江', value:  ‘zhejiang'}, {label: '杭州', value: 'hangzhou'}]

2022-05-26 02:54 UTC, miaodongqing commented on src/TreeSelect/index.md
> +## 样式类
![image](https://user-images.githubusercontent.com/1175798/170405672-fd812a26-0cb8-4724-85b8-c90b4bad3c11.png)

文档显示的效果不太对

2022-05-26 02:54 UTC, miaodongqing commented on src/TreeSelect/index.md
> +| options | TreeSelectOption[] | 是 | [] | 树形选择的数据源，目前只支持两级或三级树形选择 |
建议给出TreeSelectOption的定义

2022-05-26 02:54 UTC, miaodongqing commented on src/TreeSelect/index.md
> +| onChange | 当组件的值变化时触发 | (value: TreeSelectValue[]) => void |
建议增加异步加载[onLoadData] 参考：(https://ant.design/components/tree-select-cn/#components-tree-select-demo-async)

2022-05-31 03:45 UTC, Sxs7513 approved these changes

2022-05-31 15:24 UTC, imsenyu requested changes

2022-05-31 15:24 UTC, imsenyu commented on src/TreeSelect/index.ts
> +        const propertiesMap = new Map<
从目前的情况看，似乎发现插件上下文没放 Set/Map polyfill。。先别用

2022-05-31 15:24 UTC, imsenyu commented on src/TreeSelect/index.ts
> +        while (stack.length > 0) {
单拎一个函数出来吧。方便写测试

2022-05-31 15:24 UTC, imsenyu commented on src/TreeSelect/index.ts
> +          children: this.props.options
看起来是。。原始数据结构是只有 children 。。为了反向查找，反向设置了一遍 parent？

如果硬要这么做，建议对 this.props.options 建一个反向的数据结构（每次 options 更新就重建一遍），不要把这个逻辑放在 handleOptionTap 上。。

2022-05-31 16:14 UTC, miaodongqing commented on src/TreeSelect/index.ts
> +        const propertiesMap = new Map<
https://opendocs.alipay.com/mini/framework/implementation-detail
文档部分的set map部分最好改一下，要不然不知道有插件不兼容的坑

2022-07-12 14:06 UTC, Alpsli commented on src/TreeSelect/index.ts
> +        const propertiesMap = new Map<
这个目前代码不太好改，能在插件上注入polyfill吗

2022-08-16 07:49 UTC, Alpsli commented on src/TreeSelect/index.md
> +| onChange | 当组件的值变化时触发 | (value: TreeSelectValue[]) => void |
这个后面在提个单独feature pr

2022-11-30 04:34 UTC, closed without merging