Feat/date picker
ant-design/ant-design-mini pull request #135
Opened 2022-06-10 08:05 UTC by wyj580231

feat(DatePicker): new component

2022-06-14 04:35 UTC, miaodongqing commented on src/DatePicker/index.ts
> +      console.log(newData);
删掉

2022-06-14 04:35 UTC, miaodongqing commented on src/DatePicker/index.ts
> +  mixins: [computed, formMixin({ trigger: 'onOk' })],
当props的value 变更且不在 mini和max区间范围内， cValue超限了

2022-06-22 02:53 UTC, wyj580231 commented on src/DatePicker/index.ts
> +      this.generateData();
setData数据更改是同步的

2022-06-22 12:43 UTC, imsenyu requested changes

2022-06-22 12:43 UTC, imsenyu commented on src/DatePicker/index.ts
> +    currentValue: [], // 当前picker选中值，didmound、弹窗打开、picker变化时更新
data 目前是浅拷贝，如果尝试原地改的话，引用会共享的。。

2022-06-29 12:36 UTC, merged