feat(imageVideoUpload): add imageUpload and videoUpload
ant-design/ant-design-mini pull request #143
Opened 2022-06-15 14:59 UTC by Alpsli

- 新增 imageUpload
- 新增 videoUpload

2022-06-16 04:20 UTC, miaodongqing commented on demo/pages/ImageUpload/index.js
> +      key: '111',
demo里的key都是‘111’， key没有唯一性的要求，  对于使用者来说要感知key吗？

2022-06-16 04:20 UTC, miaodongqing commented on src/ImageUpload/index.md
> +| onAfterUpload | 使用action时，图片上传后的回调函数，当上传接口不为默认的{success: true, data: {url: 'xx'}}时使用，返回void则表示上传失败 | (res) => string |
给个说明，返回的string代表的是图片的File里的url

2022-06-16 04:20 UTC, miaodongqing commented on demo/pages/ImageUpload/index.js
> +      description: '标签3'
description可以删掉

2022-06-16 04:20 UTC, miaodongqing commented on src/ImageUpload/index.md
> +
对于用户来说，不感知key和localPath

2022-06-16 04:20 UTC, miaodongqing commented on src/ImageUpload/index.md
> +| controlled | boolean | - | false | 是否受控 |
没有controlled属性，建议删除

2022-06-22 12:36 UTC, imsenyu commented on src/VideoUpload/index.ts
> +    this.videoContext = my.createVideoContext(id || 'myVideo');
这能跑起来。。？id没传给 `<video>` 上啊

2022-06-22 12:38 UTC, imsenyu commented on src/_util/promisify.ts
> +  interface TempFile {
类型联系下 @bytemain

2022-06-22 12:41 UTC, bytemain commented on src/_util/promisify.ts
> +  interface TempFile {
目前生成类型的元数据中的 Interface 名字还是会变的，所以还没有把这些返回值或者入参的 interface 给 export 出来。已知现在有这个需求，等努努力后会把这些 interface 开放，到时候我来提 pr 修改吧

2022-06-24 08:33 UTC, Alpsli commented on src/ImageUpload/index.axml
> +        <view class="amd-image-upload-cover-loading-icon" style="background-image: url(data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%22100%25
不可以的，这个svg中间有参数的

2022-06-24 08:33 UTC, Alpsli commented on src/VideoUpload/index.axml
> +        <view class="amd-video-upload-cover-loading-icon" style="background-image: url(data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%22100%25
这个svg支持参数的

2022-06-27 04:23 UTC, imsenyu requested changes

2022-06-27 04:23 UTC, imsenyu commented on src/ImageUpload/index.axml
> +        <view class="amd-image-upload-cover-loading-icon" style="background-image: url(data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%22100%25
我搜了半天没搜到有参数？ `{{}}`

2022-06-28 05:05 UTC, Alpsli commented on demo/pages/ImageUpload/index.js
> +      key: '111',
最开始需要感知，现在不需要了

2022-06-28 05:13 UTC, Alpsli commented on src/_util/promisify.ts
> + function promisifyMy(name: string) {
这里只是不想在my的api中的success里面写处理代码，而是直接拍平可以直接 await

2022-06-28 05:23 UTC, Alpsli commented on src/VideoUpload/index.ts
> +    this.videoContext = my.createVideoContext(id || 'myVideo');
<video 
    id="{{id||'myVideo'}}" 
    
    有传的，只不过整个页面只有一个video专门用来做播放用的

2022-06-29 14:46 UTC, merged