Feat/slider new
ant-design/ant-design-mini pull request #144
Opened 2022-06-16 02:08 UTC by Alpsli

2022-06-27 04:19 UTC, imsenyu requested changes

2022-06-27 04:19 UTC, imsenyu commented on src/Slider/index.axml
> +        onTouchStart="handleTrackTouchStart"
为了跟手，还是上 SJS 吧

2022-06-27 04:19 UTC, imsenyu commented on src/Slider/index.axml
> +    style="left: {{position}}%;"
搞个 transform 实现方式?

2022-06-27 04:19 UTC, imsenyu commented on src/Slider/index.axml
> +            style="width: {{sliderWidth}}%; left: {{sliderLeft}}%"
搞个transform实现方式？

2022-08-09 09:01 UTC, Alpsli commented on src/Slider/index.axml
> +        onTouchStart="handleTrackTouchStart"
这个有节点跳动，和data有关，还是放在js吧

2022-08-16 04:39 UTC, Alpsli commented on src/Slider/index.axml
> +    style="left: {{position}}%;"
transfrom：translateX的百分比是基于当前滑块，我们这里是基于父级元素的

2022-08-16 09:35 UTC, miaodongqing approved these changes

2022-08-16 09:35 UTC, merged