feat: 添加 tabbar 组件
ant-design/ant-design-mini pull request #151
Opened 2022-06-20 13:54 UTC by charleylla

![image](https://user-images.githubusercontent.com/16316329/174617161-e46f8ead-1c37-4543-ae61-772dcdc659a8.png)

# TabBar 底部导航栏
用于在不同页面之间进行切换。

## 注意事项

- 默认 2～5 个选项卡，默认按整体宽度等分居中排布
- 可以使用 Ant Design Mini 自带的图标库或者自定义图片作为图标

## 代码示例
### 基本使用
<code src='../../demo/pages/TabBar'></code>

## 属性

#### TabBar
| 属性 | 类型 | 必填 | 默认值 | 说明 |
| -----|-----|-----|-----|----- |
| tabs | Array | 是 | [] | 底部图标配置 |
| defaultActiveKey | number | 否 |  ''  |  默认高亮的 key |
| activeColor | string | 否 |  '#1677ff'  |  高亮的颜色 |
| maxTabCount | number | 否 |  5  |  最大展示的 Tab 数量 |

## 事件

#### TabBar
| 事件名 | 说明 | 类型 |
| -----|-----|-----|
| onChange | Tab 切换时候，触发回调 |(tab: object, index: number) => void|

2022-06-27 04:17 UTC, imsenyu requested changes

2022-06-27 04:17 UTC, imsenyu commented on src/TabBar/index.axml
> +      <icon
template 别放 icon 组件，直接引用 icon template 模板
不然基础库 1.0 有潜在异常可能

2022-06-30 06:41 UTC, miaodongqing commented on src/TabBar/index.less
> +    margin-bottom: 4rpx;
我们的px单位使用@rpx， 可参考其他组件实现

2022-06-30 06:41 UTC, miaodongqing commented on src/TabBar/index.ts
> +    const { defaultActiveKey, tabs } = this.props;
defaultActiveKey建议改成activeKey, 组件内部（didUpdate里）响应activeKey的变化， 参考 https://yuque.antfin.com/docs/share/50cae65f-b87d-4633-9503-9b3f14b4f314?# 《Antd Mini设计实践指南》

2022-07-20 02:09 UTC, imsenyu commented on src/TabBar/index.axml
> +<template name="icon">
`<import src="">` 找 icon 那个 axml

2022-07-28 03:13 UTC, miaodongqing approved these changes

2022-07-28 03:13 UTC, merged