feat(ProgressCircle): new Component
ant-design/ant-design-mini pull request #154
Opened 2022-06-22 02:36 UTC by Sxs7513

2022-06-27 04:15 UTC, imsenyu requested changes

2022-06-27 04:15 UTC, imsenyu commented on src/ProgressCircle/index.ts
> +      return new Promise((resolve, reject) => {
没特殊情况的话，这里就使用 createCanvasContext ，不要用新 API 了。多端兼容性稍微好点。
不像要适配现有图形库，必须标准 Web Canvas 接口

2022-06-30 06:29 UTC, miaodongqing commented on src/ProgressCircle/index.ts
> +          this.ctx = my.createCanvasContext(this.props.id)
走到这个逻辑永远不会resolve掉， 不会一直pending中吗？

2022-06-30 06:29 UTC, miaodongqing commented on src/ProgressCircle/index.ts
> +    async getCanvasContext () {
返回的是Promise了， async可以删掉

2022-08-25 01:50 UTC, wyj580231 commented on src/ProgressCircle/index.ts
> +      setTimeout(fn, 16)
组件卸载定时器没清除

2022-08-25 06:59 UTC, miaodongqing submitted a review, later dismissed

2022-08-25 07:00 UTC, merged