feat(Rate): new Component
ant-design/ant-design-mini pull request #155
Opened 2022-06-22 02:57 UTC by Sxs7513

2022-06-27 04:14 UTC, imsenyu requested changes

2022-06-27 04:14 UTC, imsenyu commented on src/Rate/index.axml
> +<view class="amd-rate-wrapper" style="--active-color: {{activeColor}}; --inactive-color: {{inactiveColor}}">
能不用 css var 么,iOS <9.3 有兼容问题

2022-06-30 09:19 UTC, miaodongqing commented on src/Rate/index.md
> +| value | number | 否 | - | 当前数，受控值 |
不用defaultValue， 保留value， 且组件响应value的变化，参考 https://yuque.antfin.com/docs/share/50cae65f-b87d-4633-9503-9b3f14b4f314?# 《Antd Mini设计实践指南》

2022-06-30 09:19 UTC, miaodongqing commented on src/Rate/index.ts
> +      this.props.onRateEnd?.(newRate)
1. 半星模式下的选中规则与设计规范有出入

2. 缺少设计规范里的滑动打星

2022-06-30 09:19 UTC, miaodongqing commented on src/Rate/props.d.ts
> +
缺少disable， readonly属性支持

2022-08-09 12:44 UTC, miaodongqing commented on src/Rate/index.md
> +| image | string | 否 | - | 自定义图片 |
可以给个starSize选项

2022-08-09 12:44 UTC, miaodongqing commented on src/Rate/index.axml
> +        style="{{ `${ image ? `-webkit-mask-image: url(${image});` : '' } background-color: ${index + 0.5 === rate ? activeColor : (index + 1 > rate) ? (allowHalf && !image && !inactiveColor && !acti
-webkit-mask-image有没有兼容性问题？

2022-08-24 12:03 UTC, wyj580231 commented on src/Rate/index.ts
> +      this.props.onRateEnd?.(newRate)
这里会和下面的handleStarMoveEnd一起触发，可能会执行两次onRateEnd

2022-08-24 12:31 UTC, miaodongqing commented on src/Rate/props.d.ts
> +  onRateEnd?: (rate: number) => void;
onRateEnd 名字有点奇怪，建议换成onChange， 并且多暴露event类型

2022-08-24 12:31 UTC, miaodongqing commented on src/Rate/props.d.ts
> +  onRateEnd?: (rate: number) => void;
![image](https://user-images.githubusercontent.com/1175798/186418611-2a75391c-a3c5-4f1a-8923-32730e296627.png)

rate如果是absolute布局， 滑动时计算星级出错
![image](https://user-images.githubusercontent.com/1175798/186418840-dac88520-961c-4734-aa73-904894b3a018.png)

2022-09-06 11:31 UTC, miaodongqing submitted a review, later dismissed

2022-09-06 11:34 UTC, merged