feat(slider): new component
ant-design/ant-design-mini pull request #88
Opened 2022-05-12 06:20 UTC by Alpsli

-  新增 slider 组件

2022-05-16 04:22 UTC, miaodongqing requested changes

2022-05-16 04:22 UTC, miaodongqing commented on src/Slider/index.ts
> +  onInit() {
组件使用到了onInit， deriveDataFromProps生命周期， 依赖用户开启component2， 是否能用didmount， didupdate替代？

2022-05-16 04:22 UTC, miaodongqing commented on src/Slider/index.ts
> +    this.sliderId = sliderId;
this.sliderId没有消费， 是否可以删除？

2022-05-16 04:22 UTC, miaodongqing commented on src/Slider/index.ts
> +    rawValue: undefined,
this.rawValue, this.data.rawValue 是否可以只保留一个？

2022-05-16 04:22 UTC, miaodongqing commented on src/Slider/index.ts
> +        this.props.onChange?.(currentValue);
当props的defaultValue、value改变时，会触发onChange， 这一点不太合理。 一般只有内部onTouch时才会触发onChange

2022-05-16 04:22 UTC, miaodongqing commented on src/Slider/index.ts
> +      if (nextProps.value !== undefined) {
组件会响应props  value， defaultValue变更， 这两个props的界限不清晰， 建议只保留value

2022-05-16 07:26 UTC, imsenyu commented on demo/pages/Slider/index.axml
> +      defaultValue="{{80}}"
小程序组件上是不是可以加 "controlled" 来区分是否受控，而不是有 defaultValue 。
就是说 controlled=true 时，value-onChange 强联动
controlled=false 时，value-onChange 弱联动(内部维护internalValue）

2022-05-16 07:26 UTC, imsenyu commented on package.json
> +    "prepublishOnly": "npm run build:component:rpx",
revert 下？

2022-05-16 07:26 UTC, imsenyu commented on src/Slider/index.axml
> +    <slot name="icon">
template 下不要用 slot 1.0/2.0 有目前解决不了的问题

2022-05-17 09:42 UTC, Sxs7513 approved these changes

2022-05-31 15:06 UTC, imsenyu requested changes

2022-05-31 15:06 UTC, imsenyu commented on src/Slider/index.ts
> +    const sliderId = `amd-slider-id-${globalId}`;
如果要唯一 id ，可以直接用 `this.$id` ，是保持不变的且 this 实例维度唯一的

2022-06-16 02:07 UTC, closed without merging