Feat/toast
ant-design/ant-design-mini pull request #99
Opened 2022-05-17 09:34 UTC by Sxs7513

Toast 组件

2022-05-19 10:29 UTC, wyj580231 commented on demo/pages/Toast/index.acss
> +  position: fixed;
居中的样式需要使用者自己实现吗？

2022-05-19 10:29 UTC, wyj580231 commented on src/Toast/props.d.ts
> +    icon?: IconType;
icon不支持图片吗？

2022-05-19 10:29 UTC, wyj580231 commented on src/Toast/props.d.ts
> +     * @description Toast 完全关闭后的回调
是不是能像原生my.showToast一样，支持透明蒙层，防止用户点击

2022-05-26 08:11 UTC, miaodongqing commented on src/Toast/index.md
> +| afterClose | Toast 关闭后的回调 | () => void |
事件名建议都以on开头 ，比如onClose

2022-05-26 08:11 UTC, miaodongqing commented on src/Toast/index.md
> +| useMask | boolean | 否 | false | 是否展示蒙层 |
1. useMask建议改成showMask
2. 现在的逻辑是点击mask关闭toast，跟交互确认是这个逻辑吗？原生JSAPI 
 my.showToast点击蒙层是不会关闭toast的

2022-05-26 08:11 UTC, miaodongqing commented on demo/pages/Toast/index.js
> +    icon2: "MoreOutline"
加载中的交互完全依赖用户自定义实现？
...没有动起来的
组件内部能不能支持一下？

2022-05-26 08:11 UTC, miaodongqing commented on src/Toast/index.ts
> +            this.props.afterClose?.()
如果有timer， 需要clear掉 ，否则可能出现如下场景
1. 用户手动关掉toast，  但setTimeout没有清楚
2. 用户重新打开toast
3. 1里的面setTimeout执行，弹窗自动关闭

2022-05-31 15:08 UTC, imsenyu requested changes

2022-06-07 14:14 UTC, miaodongqing submitted a review, later dismissed

2022-06-08 07:14 UTC, imsenyu requested changes

2022-06-08 07:14 UTC, imsenyu commented on demo/pages/Toast/index.js
> +    image1: `url("data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%22100%25%22%20height%3D%22100%25%22%20viewBox%3D%2224%2024%2048%2048%22%3E%3C
`url()` 最好内部包掉吧

2022-06-15 04:13 UTC, closed without merging